---
title: "Demo"
author: "Xutao Wang"
date: "9/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Anderson
```{r}
GSE39939 <- readRDS('~/Desktop/RA work/build_TB_data/Signatures/Anderson/GSE39939/GSE39939_summarizedExperiemnt.RDS')
colData(GSE39939)
dim(assay(GSE39939))
```

```{r}
GSE39940 <- readRDS('~/Desktop/RA work/build_TB_data/Signatures/Anderson/GSE39940/GSE39940_summarizedExperiemnt.RDS')
colData(GSE39940)
```

## Berry
```{r}
GSE19435 <- readRDS('~/Desktop/RA work/build_TB_data/Signatures/Berry/GSE19435/GSE19435_summarizedExperiemnt.RDS')
colData(GSE19435)
```

```{r}
GSE19439 <- readRDS('~/Desktop/RA work/build_TB_data/Signatures/Berry/GSE19439/GSE19439_summarizedExperiemnt.RDS')
colData(GSE19439)
# TST: tuberculin skin test
```

```{r}
GSE19442 <- readRDS('~/Desktop/RA work/build_TB_data/Signatures/Berry/GSE19442/GSE19442_summarizedExperiemnt.RDS')
colData(GSE19442)
```


```{r}
GSE19443 <- readRDS('~/Desktop/RA work/build_TB_data/Signatures/Berry/GSE19443/GSE19443_summarizedExperiemnt.RDS')
#colnames(colData(GSE19443))[17] <- 'IsolateSensitivity'
#saveRDS(GSE19443, ascii=FALSE, file='~/Desktop/RA work/build_TB_data/Signatures/Berry/GSE19443/GSE19443_summarizedExperiemnt.RDS')
colData(GSE19443)
```


```{r}
GSE19444 <- readRDS('~/Desktop/RA work/build_TB_data/Signatures/Berry/GSE19444/GSE19444_summarizedExperiemnt.RDS')
#colnames(colData(GSE19444))[17] <- 'IsolateSensitivity'
#saveRDS(GSE19444, ascii=FALSE, file='~/Desktop/RA work/build_TB_data/Signatures/Berry/GSE19444/GSE19444_summarizedExperiemnt.RDS')
colData(GSE19444)
```


## Blankley
### Affymetrix Human Genome
```{r}
GSE54992 <- readRDS('~/Desktop/RA work/build_TB_data/Signatures/Blankley/GSE54992/GSE54992_summarizedExperiemnt.RDS')
colData(GSE54992)
# PBMC=peripheral blood mononuclear cell
```

```{r}
GSE36238 <- readRDS('~/Desktop/RA work/build_TB_data/Signatures/Blankley/GSE36238/GSE36238_summarizedExperiemnt.RDS')
colData(GSE36238)
```

```{r}
GSE31348 <- readRDS('~/Desktop/RA work/build_TB_data/Signatures/Blankley/GSE31348/GSE31348_summarizedExperiemnt.RDS')
colData(GSE31348)
```


### Agilent-019118 Human miRNA/Whole RNA Microarray
```{r}
GSE34608_micro <- readRDS('~/Desktop/RA work/build_TB_data/Signatures/Blankley/GSE34608/GSE34608_summarizedExperiemnt_micro.RDS')
colData(GSE34608_micro)
```

```{r}
GSE34608_RNA <- readRDS('~/Desktop/RA work/build_TB_data/Signatures/Blankley/GSE34608/GSE34608_summarizedExperiemnt_RNA.RDS')
colData(GSE34608_RNA)
```

## Esmail
```{r}
GSE69581 <- readRDS('~/Desktop/RA work/build_TB_data/Signatures/Esmail/GSE69581/GSE69581_summarizedExperiemnt.RDS')
colData(GSE69581)
```