---
title: "GSE39939"
author: "Xutao Wang"
date: "9/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries, message = FALSE}
library(GEOquery)
library(preprocessCore)
library(SummarizedExperiment)
library(limma)
library(dplyr)
library(illuminaHumanv4.db) # Illumina HumanHT-12 V4.0 expression beadchip
library(readxl)
```

## Read in Non-normalized data
```{r, cache = TRUE}
#setwd('~/Desktop/RA work/build_TB_data/Signatures/Anderson')
urls <- getGEOSuppFiles('GSE39939', fetch_files = FALSE)
url_non_normalized <- as.character(urls$url[2])

temp <- tempfile()
download.file(url_non_normalized,temp)

GSE39939_Non_normalized <- read.delim(gzfile(temp),row.names = 1, header = TRUE)

dim(GSE39939_Non_normalized)
```

```{r}
# Remove .Pval
GSE39939_Non_pvalue <- GSE39939_Non_normalized[,-grep('.Pval',colnames(GSE39939_Non_normalized))]
dim(GSE39939_Non_pvalue)

```

```{r get corresponding sample ID , cache=TRUE}
# Obtain raw data information from GEO
gse <- getGEO("GSE39939", GSEMatrix =  F)

description_id_raw <- sapply(1:length(names(GSMList(gse))), 
                             function(x) GSMList(gse)[[x]]@dataTable@columns$Column[3])
# Demo: Convert 6116725094_J.Detection Pval to 6116725094_J
description_id <- sapply(1:length(description_id_raw), 
                         function(x) gsub("\\..*", "", description_id_raw[x]))
ID_table <- data.frame(SampleID = names(GSMList(gse)), DescriptionID = description_id)
head(ID_table)
```


```{r mapping DescriptionID to sampleID}
# Demo: convert X6247215025_L.AVG_Signal to 6247215025_L, should use \\. when mathcing . 
colnames(GSE39939_Non_pvalue) <- sapply(1:ncol(GSE39939_Non_pvalue), 
                             function(x) gsub(".*X|\\..*", "", colnames(GSE39939_Non_pvalue)[x]))
indx <- sapply(1:length(ID_table$DescriptionID), 
              function(i) which(colnames(GSE39939_Non_pvalue) %in% ID_table$DescriptionID[i]));indx

GSE39939_Non_pvalue <- GSE39939_Non_pvalue[,indx]
colnames(GSE39939_Non_pvalue) <- ID_table$SampleID
GSE39939_Non_normalized_counts <- GSE39939_Non_pvalue
colnames(GSE39939_Non_normalized_counts)[1:10]

```

## Create Row Data
```{r convert ProbeID to Gene Symbol, cache=TURE}
# Read in data from vendor's information
GPL10558_HumanHT <- getGEO('GPL10558', GSEMatrix = F)
GPL10558_HumanHT_dat <- GPL10558_HumanHT@dataTable@table

# Annotation
PROBES <- row.names(GSE39939_Non_pvalue) # Should subsitute to Normalized file???
OUT <- AnnotationDbi::select(illuminaHumanv4.db, PROBES, "SYMBOL")
OUT[is.na(OUT)] <- NA

# Map ProbeID to Gene Symbol 
OUT_collapse <- OUT %>% group_by(PROBEID) %>% summarise(SYMBOL = paste(SYMBOL, collapse="///"), times = length(unlist(strsplit(SYMBOL, "///")))) 

GSE39939_Non_pvalue$ID_REF <- row.names(GSE39939_Non_pvalue)
GSE39939_final <- GSE39939_Non_pvalue %>% left_join(OUT_collapse, by=c('ID_REF'="PROBEID")) %>% left_join(GPL10558_HumanHT_dat, by = c('ID_REF'='ID')) 

# Create Row data annotation
row_data <- GSE39939_final %>% dplyr::select(-grep('GSM',colnames(GSE39939_final))) %>% DataFrame()
# arrange(GSE39939_final, desc(times))
```

## Create Column Data
```{r}
# Create Column Data
data_characteristic <- lapply(1:length(GSMList(gse)), function(x)  
  GSMList(gse)[[x]]@header$characteristics_ch1)
characteristic_table <- sapply(1:length(data_characteristic[[1]]), function(x) 
  sapply(data_characteristic, '[[',x)) 
## Demo convert geographical region: Kenya to Kenya
characteristic_data_frame <- sub('(.*?): ','',characteristic_table) %>% as_tibble()
characteristic_data_frame <- mutate(characteristic_data_frame, Barcode=ID_table$DescriptionID) %>% DataFrame()

#colnames(characteristic_data_frame) <- gsub(':.*','',data_characteristic[[1]])
colnames(characteristic_data_frame) <- c('TBStatus','HIVStatus','GeographicalRegion', 'Barcode')
row.names(characteristic_data_frame) <- colnames(GSE39939_Non_normalized_counts)
head(characteristic_data_frame)
```


```{r create SummarizedExperiment}
# Create Metadata
GSE39939_experimentData <- new('MIAME',
                      name="Victoria Wright",
                      lab="Wright Fleming Institute",
                      contact="v.wright@imperial.ac.uk",
                      title="Diagnosis of childhood tuberculosis and host RNA expression in Africa",
                      abstract="Children were recruited from 2 hospitals in Coast Province, Kenya (n=157) who were either HIV+ or HIV - with either active TB (culture confirmed), active TB (culture negative), LTBI or OD.",
                      url="10.1056/NEJMoa1303657",
                      pubMedIds = '24785206',
                      other=list(Platform = 'Illumina HumanHT-12 V4.0 expression beadchip (GPL10558)'))

GSE39939_summarizedExperiemnt <- SummarizedExperiment(assays = list(GSE39939_Non_normalized_counts= as.matrix(GSE39939_Non_normalized_counts)), colData = characteristic_data_frame, rowData = row_data, metadata = list(GSE39939_experimentData)); GSE39939_summarizedExperiemnt

```

```{r}
saveRDS(GSE39939_summarizedExperiemnt, ascii=FALSE, file='~/Desktop/RA work/build_TB_data/Signatures/Anderson/GSE39939/GSE39939_summarizedExperiemnt.RDS')

# Remove files in temporary directory
unlink(paste0(normalizePath(tempdir()), "/", dir(tempdir())), recursive = TRUE)
dir(tempdir()) # check the temporary directory is empty
```


## Process the Column Data 

### Make a matrix contain the NA's for the TB status cariter
#### Standard column names come from Berry GSE19443
```{r}
getwd()
geo_access <- 'GSE39939'
sobject <- readRDS(paste0(geo_access,'/',geo_access,'_summarizedExperiemnt.RDS'))
```

```{r create new column information data}
standard_name_seq <- colData(readRDS('~/Desktop/RA work/build_TB_data/Signatures/Berry/GSE19443/GSE19443_summarizedExperiemnt.RDS')) %>% data.frame() %>% colnames

new_coldata <- function(sobject){
  col_info <- colData(sobject) %>% data.frame()
  dat_NA_new <- matrix(c(rep('n.a.',length(standard_name_seq)*nrow(col_info))),ncol=length(standard_name_seq),
                             byrow=T,dimnames=list(row.names(col_info),
                                                   standard_name_seq)) %>% data.frame()
  
  # fill in with existing data
  overlap_name <- standard_name_seq[which(colnames(dat_NA_new) %in% colnames(col_info))]
  for (i in overlap_name){
    dat_NA_new[i] <- col_info[i]
  }
  
  # Append the rest of cloumns to the dataframe
  col_info_rest <- col_info %>% dplyr::select(-overlap_name)
  dat_final <- cbind(dat_NA_new,col_info_rest)
  
  return(dat_final)
}
new_col_info <- new_coldata(sobject)
```

# Rename TBstatus
### PTB: active TB
### Latent
### Control
### OD: other disease
```{r}

relabel_TB <- function(dat_new){
  dat_new$culture_status <- sub(".*\\((.*)\\).*", "\\1", dat_new$TBStatus)
  
  dat_new$culture_status <- ifelse(dat_new$culture_status==dat_new$TBStatus,'n.a.',dat_new$culture_status)
  
  TBStatus <- TBStatus_temp <- dat_new$TBStatus
  
  for (i in 1:length(TBStatus)){
  if (TBStatus[i] == unique(TBStatus_temp)[1] || TBStatus[i] == unique(TBStatus_temp)[4]){
    TBStatus[i] = 'PTB'
  }
    if (TBStatus[i] == unique(TBStatus_temp)[2] || TBStatus[i] == unique(TBStatus_temp)[5]){
    TBStatus[i] = 'OD'
  }
    if (TBStatus[i] == unique(TBStatus_temp)[3]){
    TBStatus[i] = 'Latent'
  }
  }
  dat_new$TBStatus <- TBStatus
  return(dat_new)
}

new_col_info <- relabel_TB(new_col_info) 
new_col_info %>% View()

colData(sobject) <- new_col_info %>% DataFrame()

saveRDS(sobject,paste0(geo_access,'/',geo_access,'_sobject.RDS'))

```







