---
title: "GSE19442"
author: "Xutao Wang"
date: "9/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message = FALSE, cache=TRUE}
library(GEOquery)
library(preprocessCore)
library(SummarizedExperiment)
library(limma)
library(dplyr)
library(illuminaHumanv3.db) # Illumina HumanHT-12 V3.0 expression beadchip
```

## Read in Non-normalized data
```{r, cache = TRUE}
#setwd('~/Desktop/RA work/build_TB_data/Signatures/Berry')
#getwd()
urls <- getGEOSuppFiles("GSE19442", fetch_files = FALSE)
url_cel <- as.character(urls$url[1])
temp <- tempfile()
tempd <- tempdir()
download.file(url_cel,temp)
untar(temp,exdir = tempd)
#untar('GSE19442/GSE19442_RAW.tar', exdir="GSE19442/GSE19442_Raw")
files <- list.files(tempd, pattern = "txt.*");files
GSE19442_Non_normalized_list <- lapply(files, function(x) read.delim(paste0(tempd,'/',x), header=TRUE, col.names = c('ID_REF',gsub('_.*','',x),paste0(gsub('_.*','',x),'.Pval')), stringsAsFactors = FALSE))

```

## Check ID_REF for each data
```{r}
GSE19442_Non_normalized_list_ID <- sapply(GSE19442_Non_normalized_list, function(x) x[,1]) %>% data.frame()
# check they have identical ID_REF
check_1 <- sapply(1:ncol(GSE19442_Non_normalized_list_ID),function(x) all(GSE19442_Non_normalized_list_ID[,1]==GSE19442_Non_normalized_list_ID[,x]));check_1
# No problem, all true
```

# Create Non-normalized data
```{r}
GSE19442_Non_normalized <- do.call(cbind,GSE19442_Non_normalized_list)
GSE19442_Non_normalized <- GSE19442_Non_normalized[,-which(colnames(GSE19442_Non_normalized)=='ID_REF')[-1]]
row.names(GSE19442_Non_normalized) <- GSE19442_Non_normalized$ID_REF
#dim(GSE19442_Non_normalized)
```


```{r}
# Remove .Pval
GSE19442_Non_pvalue <- GSE19442_Non_normalized[,-c(1,grep('.Pval',colnames(GSE19442_Non_normalized)))]
GSE19442_Non_normalized_counts <- GSE19442_Non_pvalue
dim(GSE19442_Non_pvalue)
```

```{r convert ProbeID to Gene Symbol, cache=TURE}
# Annotation
PROBES <- row.names(GSE19442_Non_pvalue) # Should subsitute to Normalized file???
OUT <- AnnotationDbi::select(illuminaHumanv3.db, PROBES, "SYMBOL")
OUT[is.na(OUT)] <- 'Unmapped'

# Map ProbeID to Gene Symbol 
OUT_collapse <- OUT %>% group_by(PROBEID) %>%  # Multiple gene symbols map to the same ProbeID
  summarise(SYMBOL = paste(SYMBOL, collapse=", "), times = length(unlist(strsplit(SYMBOL, ",")))) 

GSE19442_Non_pvalue$ID_REF <- row.names(GSE19442_Non_pvalue)
GSE19442_final <- GSE19442_Non_pvalue %>% left_join(OUT_collapse, by=c('ID_REF'="PROBEID")) %>% as_tibble()

#arrange(GSE19442_final, desc(times))

```

## Create colData
```{r create column data}
gse <- getGEO("GSE19442", GSEMatrix =  F)
data_characteristic <- lapply(1:length(GSMList(gse)), function(x)  
  GSMList(gse)[[x]]@header$characteristics_ch1)
characteristic_table <- sapply(1:length(data_characteristic[[1]]), function(x) 
  sapply(data_characteristic, '[[',x)) 
## Demo convert geographical region: Kenya to Kenya
characteristic_data_frame <- sub('(.*?): ','',characteristic_table) %>% DataFrame()
#colnames(characteristic_data_frame) <- gsub(':.*','',data_characteristic[[1]])
colnames(characteristic_data_frame) <- c('Age','Gender','Ethnicity','TBStatus','GeographicalRegion','BcgVaccinated','BirthRegion','TST', 'SputumSmearStatus','sputum_culture')

row.names(characteristic_data_frame) <- colnames(GSE19442_Non_normalized_counts)
head(characteristic_data_frame)
```


```{r Create RowData MetaData and summarized experiment}
# Create Row data annotation
row_data <- DataFrame(SYMBOL=GSE19442_final$SYMBOL)

# Create Metadata
GSE19442_experimentData <- new('MIAME',
                      name="Damien Chaussabel",
                      lab="Baylor Institute for Immunology Research",
                      contact="DChaussabel@benaroyaresearch.org",
                      title="An interferon-inducible neutrophil-driven blood transcriptional signature in human tuberculosis",
                      abstract="An example SummarizedExperimentObject",
                      url="10.1038/nature09247",
                      pubMedIds = '20725040',
                      other=list(Platform = 'Illumina HumanHT-12 V3.0 expression beadchip'))

GSE19442_summarizedExperiemnt <- SummarizedExperiment(assays = list(GSE19442_Non_normalized_counts= as.matrix(GSE19442_Non_normalized_counts)), colData = characteristic_data_frame, rowData = row_data, metadata = list(GSE19442_experimentData)); GSE19442_summarizedExperiemnt

```

```{r}
saveRDS(GSE19442_summarizedExperiemnt, ascii=FALSE, file='GSE19442/GSE19442_summarizedExperiemnt.RDS')

# Remove files in temporary directory
unlink(paste0(normalizePath(tempdir()), "/", dir(tempdir())), recursive = TRUE)
dir(tempdir()) # check the temporary directory is empty
```
