---
title: "GSE19444"
author: "Xutao Wang"
date: "10/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message = FALSE, cache=TRUE}
library(GEOquery)
library(preprocessCore)
library(SummarizedExperiment)
library(limma)
library(dplyr)
library(illuminaHumanv3.db) # Illumina HumanHT-12 V3.0 expression beadchip
```

```{r, cache = TRUE}
setwd('~/Desktop/RA work/build_TB_data/Signatures/Berry')
getwd()

urls <- getGEOSuppFiles("GSE19444", fetch_files = FALSE)
url_cel <- as.character(urls$url[1])
temp <- tempfile()
tempd <- tempdir()
download.file(url_cel,temp)
untar(temp,exdir = tempd)

#untar('GSE19444/GSE19444_RAW.tar', exdir="GSE19444/GSE19444_Raw")
files <- list.files(tempd, pattern = "txt.*");files

## Special handling for GSM484599_LTB_LON_test009.txt.gz
GSE19444_Non_normalized_list <-lapply(files[-which(files=='GSM484599_LTB_LON_test009.txt.gz')],
                                      function(x) read.delim(paste0(tempd,'/',x),  header=TRUE, col.names = c('ID_REF',gsub('_.*','',x),paste0(gsub('_.*','',x),'.Pval')), stringsAsFactors = FALSE))

```

## Check the names of ID_REF in each dataset
```{r}
GSE19444_Non_normalized_list_ID <- sapply(GSE19444_Non_normalized_list, function(x) x[,1]) %>% data.frame()
# check they have identical ID_REF
check_1 <- sapply(1:ncol(GSE19444_Non_normalized_list_ID),function(x) all(GSE19444_Non_normalized_list_ID[,1]==GSE19444_Non_normalized_list_ID[,x]));check_1
sum(check_1!=T)
# No problem, all true
```

## Combine two datasets, get the final non-normalized data
```{r}
GSE19444_Non_normalized_temp <- do.call(cbind,GSE19444_Non_normalized_list)

# Remove redudant Column ID
GSE19444_Non_normalized_temp <- GSE19444_Non_normalized_temp[,-which(colnames(GSE19444_Non_normalized_temp)=='ID_REF')[-1]]

## Special handling for GSM484599_LTB_LON_test009.txt.gz
GSM484599 <- na.omit(read.delim(paste0(tempd,'/GSM484599_LTB_LON_test009.txt.gz'), stringsAsFactors = FALSE))
colnames(GSM484599) <- c('ID_REF','GSM484599','GSM484599.Pval')

# Combine the data
GSE19444_Non_normalized <- GSE19444_Non_normalized_temp %>% inner_join(GSM484599, by= c('ID_REF'="ID_REF")) %>% data.frame()
row.names(GSE19444_Non_normalized) <- GSE19444_Non_normalized$ID_REF
```


```{r}
# Remove .Pvals
GSE19444_Non_pvalue <- GSE19444_Non_normalized[,-c(1,grep('.Pval',colnames(GSE19444_Non_normalized)))]

# Create Expression Matrix
GSE19444_Non_normalized_counts <- GSE19444_Non_pvalue
dim(GSE19444_Non_pvalue)
```

```{r convert ProbeID to Gene Symbol, cache=TURE}
# Annotation from vendor's information
gpl6947 <- getGEO("GPL6947", GSEMatrix =  F)
GPL6947_dat <- gpl6947@dataTable@table %>% data.frame()

# Annotation from Bioconductor package
PROBES <- row.names(GSE19444_Non_pvalue)
OUT <- AnnotationDbi::select(illuminaHumanv3.db, PROBES, "SYMBOL")
OUT[is.na(OUT)] <- NA

# Map ProbeID to Gene Symbol 
OUT_collapse <- OUT %>% group_by(PROBEID) %>% summarise(SYMBOL = paste(SYMBOL, collapse="///"), times = length(unlist(strsplit(SYMBOL, "///")))) 

GSE19444_Non_pvalue$ID_REF <- row.names(GSE19444_Non_pvalue)
GSE19444_final <- GSE19444_Non_pvalue %>% left_join(OUT_collapse, by=c('ID_REF' = "PROBEID")) %>% left_join(GPL6947_dat, by = c('ID_REF'='ID')) 

row_data <- GSE19444_final %>% dplyr::select(-grep('GSM',colnames(GSE19444_final))) %>% DataFrame()

#arrange(GSE19444_final, desc(times))
```

```{r create column data}
gse <- getGEO("GSE19444", GSEMatrix =  F)
data_characteristic <- lapply(1:length(GSMList(gse)), function(x)  
  GSMList(gse)[[x]]@header$characteristics_ch1)
characteristic_table <- sapply(1:length(data_characteristic[[1]]), function(x) 
  sapply(data_characteristic, '[[',x)) 
## Demo convert geographical region: Kenya to Kenya
characteristic_data_frame <- sub('(.*?): ','',characteristic_table) %>% DataFrame()
#colnames(characteristic_data_frame) <- gsub(':.*','',data_characteristic[[1]])
colnames(characteristic_data_frame) <- c('Age','Gender','Ethnicity','TBStatus','GeographicalRegion','BcgVaccinated','BirthRegion','TST',
'exposure_latent', 'index_case_disease_site', 'smear_of_index_case', 'modal_x_ray_grade','SputumSmearStatus','sputum_culture', 'bal_smear', 'bal_culture','isolate_sensitivity')
indx <- sapply(1:length(names(GSMList(gse))), function(i) 
  which(names(GSMList(gse)) %in% colnames(GSE19444_Non_normalized_counts)[i]));indx
characteristic_data_frame <- characteristic_data_frame[indx,]
row.names(characteristic_data_frame) <- colnames(GSE19444_Non_normalized_counts)
tail(characteristic_data_frame)
```

```{r Create RowData MetaData and summarized experiment}
# Create Metadata
GSE19444_experimentData <- new('MIAME',
                      name="Damien Chaussabel",
                      lab="Baylor Institute for Immunology Research",
                      contact="DChaussabel@benaroyaresearch.org",
                      title="An interferon-inducible neutrophil-driven blood transcriptional signature in human tuberculosis",
                      abstract="An example SummarizedExperimentObject",
                      url="10.1038/nature09247",
                      pubMedIds = '20725040',
                      other=list(Platform = 'Illumina HumanHT-12 V3.0 expression beadchip (GPL6947)'))

GSE19444_summarizedExperiemnt <- SummarizedExperiment(assays = list(GSEGSE19444_Non_normalized_counts= as.matrix(GSE19444_Non_normalized_counts)), colData = characteristic_data_frame, rowData = row_data, metadata = list(GSE19444_experimentData)); GSE19444_summarizedExperiemnt

```

```{r}
saveRDS(GSE19444_summarizedExperiemnt, ascii=FALSE, file='GSE19444/GSE19444_summarizedExperiemnt.RDS')

# Remove files in temporary directory
unlink(paste0(normalizePath(tempdir()), "/", dir(tempdir())), recursive = TRUE)
dir(tempdir()) # check the temporary directory is empty
```

### Make a matrix contain the NA's for the TB status cariter
#### Standard column names come from Berry GSE19443
```{r}
getwd()
geo_access <- 'GSE19444'
sobject <- readRDS(paste0(geo_access,'/',geo_access,'_summarizedExperiemnt.RDS'))
```

```{r create new column information data}
standard_name_seq <- colData(readRDS('~/Desktop/RA work/build_TB_data/Signatures/Berry/GSE19443/GSE19443_summarizedExperiemnt.RDS')) %>% data.frame() %>% colnames
new_coldata <- function(sobject){
  col_info <- colData(sobject) %>% data.frame()
  dat_NA_new <- matrix(c(rep('n.a.',length(standard_name_seq)*nrow(col_info))),ncol=length(standard_name_seq),
                             byrow=T,dimnames=list(row.names(col_info),
                                                   standard_name_seq)) %>% data.frame()
  
  # fill in with existing data
  overlap_name <- standard_name_seq[which(colnames(dat_NA_new) %in% colnames(col_info))]
  for (i in overlap_name){
    dat_NA_new[i] <- col_info[i]
  }
  
  # Append the rest of cloumns to the dataframe
  col_info_rest <- col_info %>% dplyr::select(-overlap_name)
  dat_final <- cbind(dat_NA_new,col_info_rest)
  
  return(dat_final)
}

new_col_info <- new_coldata(sobject)

```

# Rename TBstatus
### PTB: active TB
### Latent
### Control
### OD: other disease
```{r}
TBStatus <- TBStatus_temp <- as.character(new_col_info$TBStatus)
unique(TBStatus_temp)
TBStatus <- ifelse(TBStatus_temp=="Control (BCG+)","Control",TBStatus_temp)
new_col_info$TBStatus <- TBStatus

new_col_info %>% View()

colData(sobject) <- new_col_info %>% DataFrame()
```

# Edit Row Data

```{r}
row_data <- rowData(sobject) %>% data.frame()
create_gene_symbol <- function(sobject){
  row_data <- rowData(sobject) %>% data.frame()
  Symbol_R <- row_data$SYMBOL 
  Symbol_plat <- row_data$Symbol
  
  # Use platform annotation as reference 
  Symbol_plat_new <- Symbol_plat
  for (i in 1:length(Symbol_R)){
    if (Symbol_plat_new[i]==""){
    Symbol_plat_new[i] = Symbol_R[i]
    }
  }
  row_data$SYMBOL_NEW <- Symbol_plat_new
  
  return(row_data)
}

create_gene_symbol(sobject) %>% View()
rowData(sobject) <- create_gene_symbol(sobject) %>% DataFrame()

saveRDS(sobject,paste0(geo_access,'/',geo_access,'_sobject.RDS'))

```
