---
title: "GSE94438"
author: "Xutao Wang"
date: "10/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(GEOquery)
library(preprocessCore)
library(SummarizedExperiment)
library(dplyr)
# Illumina HiSeq 2000 (Homo sapiens)
```

## READ in data and create Row data
```{r}
urls <-  getGEOSuppFiles("GSE94438",fetch_files = FALSE)
url_non_normalized <- as.character(urls$url[2])
temp <- tempfile()
download.file(url_non_normalized,temp)

GSE94438_Non_normalized <- read.csv(gzfile(temp), row.names = 1, header = TRUE)

# head(colnames(GSE94438_Non_normalized))
# Obtain row data information from the raw data

row_data <- GSE94438_Non_normalized %>% dplyr::select(c('symbol')) %>% DataFrame()
row_data$ID_REF <- rownames(GSE94438_Non_normalized)
row_data$SYMBOL_NEW <- row_data$symbol

# Remove symbol, re name column names
GSE94438_Non_normalized_counts <- GSE94438_Non_normalized[,-1]

colnames(GSE94438_Non_normalized_counts) <- gsub(".*X","",colnames(GSE94438_Non_normalized_counts))
```

## Create read couns matrix and ColumnData
```{r}
gse <- getGEO("GSE94438", GSEMatrix = FALSE)
data_characteristic <- lapply(1:length(GSMList(gse)), function(x)  
  GSMList(gse)[[x]]@header$characteristics_ch1)
characteristic_table <- sapply(1:length(data_characteristic[[1]]), function(x) 
  sapply(data_characteristic, '[[',x)) 
head(characteristic_table)

characteristic_data_frame <- sub('(.*?): ','',characteristic_table) %>% data.frame()
colnames(characteristic_data_frame) <- c('Tissue',"Code","PatientID","GeographicRegion","Age","Gender","TBStatus","TimeFromExposure","TimeToTB")
characteristic_data_frame$SampleID <- names(GSMList(gse))

characteristic_data_frame <- characteristic_data_frame %>% distinct(Code, .keep_all = TRUE)

index <- sapply(1:nrow(characteristic_data_frame), function(i) which(colnames(GSE94438_Non_normalized_counts) %in% characteristic_data_frame$Code[i]))

GSE94438_raw_counts <- GSE94438_Non_normalized_counts[,index]
colnames(GSE94438_raw_counts) <- characteristic_data_frame$SampleID

# Create Column Data
row.names(characteristic_data_frame) <- characteristic_data_frame$SampleID
characteristic_data_frame$Tissue <- "Whole Blood"

TBStatus_temp <- as.character(characteristic_data_frame$TBStatus)
TBStatus <- ifelse(TBStatus_temp == "case (TB)","PTB",TBStatus_temp)

characteristic_data_frame$TBStatus <- TBStatus

characteristic_data_frame$Gender <- ifelse(characteristic_data_frame$Gender=="M","Male","Female")

characteristic_data_frame_final <- characteristic_data_frame[,-grep("SampleID",colnames(characteristic_data_frame))] %>% DataFrame()
View(characteristic_data_frame_final)
```

## Create Summarized Experiment
```{r}
# Create Metadata
GSE94438_experimentData <- new('MIAME',
                      name="Daniel Zak",
                      lab="Center for Infectious Disease Research",
                      contact="danielzak000@gmail.com",
                      title="Four-gene Pan-African Blood Signature Predicts Progression to Tuberculosis.",
                      abstract="Samples are collected from subjects in a household contact study after a person comes back to the household, diagnosed with TB. Samples are collected every 6 months upto, 18 months. Some people go on to develop TB (cases) where as some others do not (controls). Here we are trying to establish a gene signature to predict the occurance of TB.",
                      url="10.1164/rccm.201711-2340OC",
                      pubMedIds = '29624071',
                      other=list(Platform = 'Illumina HiSeq 2000 (Homo sapiens): GPL11154'))


GSE94438_summarizedExperiemnt <- SummarizedExperiment(assays = list(GSE94438_Non_normalized_counts= as.matrix(GSE94438_raw_counts)), colData = characteristic_data_frame_final, rowData = row_data, metadata = list(GSE94438_experimentData)); GSE94438_summarizedExperiemnt

```

```{r}
saveRDS(GSE94438_summarizedExperiemnt, ascii=FALSE, file='GSE94438/GSE94438_summarizedExperiemnt.RDS')

# Remove files in temporary directory
unlink(paste0(normalizePath(tempdir()), "/", dir(tempdir())), recursive = TRUE)
dir(tempdir()) # check the temporary directory is empty
```

### Make a matrix contain the NA's for the TB status cariter
#### Standard column names come from Berry GSE19443
```{r}
getwd()
geo_access <- 'GSE94438'
sobject <- readRDS(paste0(geo_access,'/',geo_access,'_summarizedExperiemnt.RDS'))
```

```{r create new column information data}
standard_name_seq <- colData(readRDS('~/Desktop/RA work/build_TB_data/Signatures/Berry/GSE19443/GSE19443_summarizedExperiemnt.RDS')) %>% data.frame() %>% colnames
new_coldata <- function(sobject){
  col_info <- colData(sobject) %>% data.frame()
  dat_NA_new <- matrix(c(rep('n.a.',length(standard_name_seq)*nrow(col_info))),ncol=length(standard_name_seq),
                             byrow=T,dimnames=list(row.names(col_info),
                                                   standard_name_seq)) %>% data.frame()
  
  # fill in with existing data
  overlap_name <- standard_name_seq[which(colnames(dat_NA_new) %in% colnames(col_info))]
  for (i in overlap_name){
    dat_NA_new[i] <- col_info[i]
  }
  
  # Append the rest of cloumns to the dataframe
  col_info_rest <- col_info %>% dplyr::select(-overlap_name)
  dat_final <- cbind(dat_NA_new,col_info_rest)
  
  return(dat_final)
}

new_col_info <- new_coldata(sobject)

colData(sobject) <- new_col_info %>% DataFrame()

saveRDS(sobject,paste0(geo_access,'/',geo_access,'_sobject.RDS'))
```


































