---
title: "Brazil Validation"
author: "Xutao Wang"
date: "6/30/2020"
output:
  BiocStyle::html_document:
    code_folding: "hide"
    toc_float: true
  BiocStyle::pdf_document: default
package: BiocStyle
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message=FALSE}
library(BiocParallel)
library(dplyr)
library(DESeq2)
library(edgeR)
library(GEOquery)
library(MultiAssayExperiment)
library(SummarizedExperiment)
library(caret)

devtools::load_all()
library(curatedTBData)
```

# Load and clean data
```{r, results='hide'}
gse_progress <- c("GSE79362", "GSE107994","GSE94438","GSE112104")
progress_raw <- get_curatedTBData(gse_progress)

# Filter genes with counts consistenly low across samples
MaxFilter <- function(df, max.value = 10){
  df.filtered <- df[which(apply(df,1,max) >= max.value),]
  return(df.filtered)
}

# IQR filter
IQR_Filter <- function(df, top.n.or.ratio, use.ratio = FALSE){
  gene.vec.sorted <- rownames(df)[order(-apply(as.matrix(df), 1, IQR))]
  if (use.ratio == TRUE){
    top.n.or.ratio <- round(top.n.or.ratio * nrow(df))
    df.output <- df[which(rownames(df) %in% gene.vec.sorted[1:top.n.or.ratio]),]
  } else{
    df.output <- df[which(rownames(df) %in% gene.vec.sorted[1:top.n.or.ratio]),]
  }
  return(df.output)
}

## Data cleaning for Africa data
counts.africa.baseline <- progress_raw$GSE79362[["assay_reprocess"]]
# Max 5 filter.
counts.africa.baseline.filtered <- MaxFilter(counts.africa.baseline, 5)
# Normalization
counts.africa.baseline.norm <- DESeq2::vst(counts.africa.baseline.filtered)
# IQR filter
# counts.africa.baseline.IQR <- IQR_Filter(counts.africa.baseline.norm, 0.9, use.ratio = TRUE)
# "MOB3C" not found in GSE79362 if using IQR

GSE79362_train_full <- SummarizedExperiment(list(counts=counts.africa.baseline.norm),
                                            colData = colData(progress_raw$GSE79362))

# Select samples at baseline
sample_baseline <- colData(GSE79362_train_full)[-nrow(GSE79362_train_full),
                   c("PatientID","MeasurementDay")] %>% 
  data.frame() %>% 
  mutate(sample_name=row.names(colData(GSE79362_train_full))) %>% 
  dplyr::group_by(PatientID) %>%
  dplyr::mutate(first = dplyr::first(sample_name))

# 40 progressor and 105 non-progressor
GSE79362_train_sub <- GSE79362_train_full[,unique(sample_baseline$first)]

# Data Cleaning for Brazil
counts.brazil.baseline <- progress_raw$GSE112104[["assay_reprocess"]]
# Max 5 filter
counts.brazil.baseline.filtered <- MaxFilter(counts.brazil.baseline, 5)
# Normalization
counts.brazil.baseline.norm <- DESeq2::vst(counts.brazil.baseline.filtered)

# IQR filter
# counts.brazil.baseline.IQR <- IQR_Filter(counts.brazil.baseline.norm, 0.9, use.ratio = TRUE)


GSE112104_test_full <- SummarizedExperiment(list(counts=counts.brazil.baseline.norm),
                                            colData = colData(progress_raw$GSE112104))

# Select samples with progression information: 
# 21 progressor 16 non-progressor
GSE112104_test_sub <- GSE112104_test_full[,GSE112104_test_full$Progression %in% c("Positive","Negative")]

```

# Batch correction
```{r, results='hide', message=FALSE}
# Combine training and testing data
object_list <- list(GSE79362=GSE79362_train_sub,
                    GSE112104=GSE112104_test_sub)

dat_exprs_match <- lapply(object_list, function(x)
        SummarizedExperiment::assays(x)[[1]] %>% data.frame)
dat_exprs_combine <- Reduce(
    function(x, y) merge(x, y, by = "id", all = FALSE),
    lapply(dat_exprs_match, function(x) { x$id <- rownames(x); x }))
row_names <- dat_exprs_combine$id
dat_exprs_count <- dat_exprs_combine %>% 
                   dplyr::select(-.data$id) %>% data.frame()
row.names(dat_exprs_count) <- row_names

col_data <- lapply(seq_len(length(object_list)), function(x) {
    col_data <- SummarizedExperiment::colData(object_list[[x]])
    col_data$GSE <-names(object_list[x])
    col_data
  })
  col_info <- plyr::rbind.fill(lapply(col_data,function(x){as.data.frame(x)}))


batch1 <- c(rep("traning",ncol(GSE79362_train_sub)),
            rep("testing",ncol(GSE112104_test_sub)))

mod1 <- model.matrix(~as.factor(Progression),data = col_info)

combat_edata <- sva::ComBat(dat=dat_exprs_count, batch=batch1,
                            mod=mod1,mean.only=F)

dat_train <- combat_edata[,1:ncol(GSE79362_train_sub)]
dat_test <- combat_edata[,(ncol(GSE79362_train_sub)+1):ncol(combat_edata)]

# Subset data that only includes features from the Leong_RISK_29
annotationColName <- "Progression"
annotationCase <- "Positive"
signatureName <- "Leong_RISK_29" 
signatureGenes <- TBSignatureProfiler::TBsignatures[[signatureName]]

dat_train_sig <- assay(dat_train) %>% data.frame() %>%
    dplyr::filter(row.names(dat_train) %in% signatureGenes) %>%
    t() %>% data.frame()
GSE79362_progress <- as.factor(colData(GSE79362_train_sub)[,annotationColName])
#progress_status_train <- ifelse(GSE79362_progress == annotationCase, 1, 0) %>% make.names() %>% as.factor()
progress_status_train <- as.factor(colData(GSE79362_train_sub)[,annotationColName])

dat_test_sig <- dat_test %>% data.frame() %>%
    dplyr::filter(row.names(dat_test) %in% signatureGenes) %>%
    t() %>% data.frame()
GSE112104_progress <- colData(GSE112104_test_sub)[,annotationColName]

#progress_status_test <- ifelse(GSE112104_progress == annotationCase, 1, 0) %>% 
#  make.names() %>% as.factor()
progress_status_test <- as.factor(colData(GSE112104_test_sub)[,annotationColName])
```

# Evaluate Leong\_RISK\_29{.tabset}

## Use Model selection
```{r, results="hide", message=FALSE}
source("~/Desktop/RA work/build_TB_data/Signatures/Leong/Model Fitting/model_selection.R")

data.example <- list(df.training=dat_train_sig, df.testing=dat_test_sig, 
                     y.train=colData(GSE79362_train_sub)[,annotationColName],
                     y.test=colData(GSE112104_test_sub)[,annotationColName])

data.prepared <- prepareData(df.training = data.example$df.training,
                             df.testing = data.example$df.testing,
                             y.train = data.example$y.train,
                             y.test = data.example$y.test,
                             positive = "Positive")

## Data normalization/scaling
data.norm <- normData(training = data.prepared$training,
                      testing = data.prepared$testing)


### Model selection
model.selection.output <- modelSelection(df.training = data.norm$trainTransformed,
                      model.names = c("glmnet","ranger"),
                      num.cv.fold = 5,
                      num.cv.repeat = 5,
                      num.param.tune = 6,
                      seed.use = 800,
                      show.some.models = TRUE)

prediction_single_list <- lapply(model.selection.output$list.model.fit[1:2], 
                                 function(x) predictAndEvaluation(
                                    model.best = x,
                                    test.data = data.norm$testTransformed,
                                    prevalence = 0.1,
                                    is.ensemble = FALSE))
```

```{r}
prediction_single_list$glmnet$roc
```

```{r}
prediction_single_list$ranger$roc
```

## glmnet
```{r}
num.cv.fold = 10
num.cv.repeat = 10
num.param.tune = 12
seed.use = 100

# cv_5 <- caret::trainControl(method = "cv", number = 5)
# Model training general parameters setting
fitControl <- trainControl(method = "repeatedcv",
                           number = num.cv.fold,
                           repeats = num.cv.repeat,
                           ## Estimate class probabilities
                           classProbs = TRUE,
                           savePredictions = TRUE,
                           ## parallel in windows:
                           allowParallel = TRUE,
                           ## Evaluate performance using
                           ## the following function
                           summaryFunction = twoClassSummary)

preProcValues <- preProcess(cbind(dat_train_sig,progress_status_train), method = c("center", "scale"))

dat_train_sig_scale <- predict(preProcValues,
                               cbind(dat_train_sig, Class = progress_status_train))
dat_test_sig_scale <- predict(preProcValues,
                              cbind(dat_test_sig, Class = progress_status_test))

model_train_glmnet <- caret::train(Class ~ ., 
                                   data = dat_train_sig_scale, 
                                   method = "glmnet", 
                                   trControl = fitControl, 
                                   metric = "Sens",
                                   maximize = TRUE)

predict_result_glmnet <- stats::predict(model_train_glmnet, 
                                        dat_test_sig_scale, type="prob")
# predict_result_glmnet %>% View

ROCit::rocit(predict_result_glmnet[,2],
            dat_test_sig_scale$Class)$AUC

```

## ranger
```{r}
model_train_rf <- caret::train(Class ~ ., 
                               data = dat_train_sig_scale, 
                               method = "ranger", num.trees = 1000,
                               num.threads = 6, 
                               classification = TRUE,
                               trControl = fitControl)
# Exclude "mtry" argument

predict_result_rf <- stats::predict(model_train_rf, dat_test_sig_scale, type="prob")

ROCit::rocit(predict_result_rf[,2],
             dat_test_sig_scale$Class)$AUC

```

