---
title: "GSE42830"
author: "Xutao Wang"
date: "10/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message = FALSE, cache=TRUE}
library(GEOquery)
library(preprocessCore)
library(SummarizedExperiment)
library(limma)
library(dplyr)
library(illuminaHumanv4.db) # Illumina HumanHT-12 V4.0 expression beadchip
library(GEOmetadb)
```

```{r}
urls <- getGEOSuppFiles('GSE42830', fetch_files = FALSE);urls
url_non_normalized <- as.character(urls$url[2])

temp <- tempfile()
download.file(url_non_normalized,temp)

GSE42830_Non_normalized <- read.delim(gzfile(temp),row.names = 1, header = TRUE) %>% dplyr::select_if(~sum(!is.na(.)) > 0)
dim(GSE42830_Non_normalized)
```


```{r}
# Renaming column names, remove .pVal
GSE42830_Non_pvalue <- GSE42830_Non_normalized[,-grep('.Pval',colnames(GSE42830_Non_normalized))]
GSE42830_Non_normalized_counts <- GSE42830_Non_normalized[,-grep('.Pval',colnames(GSE42830_Non_normalized))]
dim(GSE42830_Non_pvalue)

gse <- getGEO("GSE42830", GSEMatrix =  F)
colnames(GSE42830_Non_pvalue) <- names(GSMList(gse))
colnames(GSE42830_Non_normalized_counts) <- names(GSMList(gse))
colnames(GSE42830_Non_normalized_counts)
```

```{r convert ProbeID to Gene Symbol, cache=TURE}
# Read in data from vendor's information
GPL10558_HumanHT <- getGEO('GPL10558', GSEMatrix = F)
GPL10558_HumanHT_dat <- GPL10558_HumanHT@dataTable@table

# Annotation
PROBES <- row.names(GSE42830_Non_pvalue) # Should subsitute to Normalized file???
OUT <- AnnotationDbi::select(illuminaHumanv4.db, PROBES, "SYMBOL")
OUT[is.na(OUT)] <- NA

# Map ProbeID to Gene Symbol 
OUT_collapse <- OUT %>% group_by(PROBEID) %>%  # Multiple gene symbols map to the same ProbeID
  summarise(SYMBOL = paste(SYMBOL, collapse="///"), times = length(unlist(strsplit(SYMBOL, "///")))) 

GSE42830_Non_pvalue$ID_REF <- row.names(GSE42830_Non_pvalue)
GSE42830_final <- GSE42830_Non_pvalue %>% left_join(OUT_collapse, by=c('ID_REF'="PROBEID")) %>% left_join(GPL10558_HumanHT_dat, by = c('ID_REF'='ID')) 

# Create Row data annotation
row_data <- GSE42830_final %>% dplyr::select(-grep('GSM',colnames(GSE42830_final))) %>% DataFrame()
```

```{r create SummarizedExperiment}
# Create Metadata
GSE42830_experimentData <- new('MIAME',
                      name="Chole Bloom",
                      lab="MRC National Institute for Medical Research",
                      contact="cbloom@nimr.mrc.ac.uk",
                      title="Transcriptional blood signatures distinguish pulmonary tuberculosis, pulmonary sarcoidosis, pneumonias and lung cancers.",
                      abstract="Overall Design: There were 16 TB, 25 sarcoidosis, 8 pneumonia, 8 lung cancer and 38 healthy controls
",
                      url="10.1371/journal.pone.0070630",
                      pubMedIds = '23940611',
                      other=list(Platform = 'Illumina HumanHT-12 V4.0 expression beadchip (GPL10558)'))

# Create Column Data
data_characteristic <- lapply(1:length(GSMList(gse)), function(x)  
  GSMList(gse)[[x]]@header$characteristics_ch1)
characteristic_table <- sapply(1:length(data_characteristic[[1]]), function(x) 
  sapply(data_characteristic, '[[',x)); characteristic_table
## Demo convert geographical region: Kenya to Kenya
characteristic_data_frame <- sub('(.*?): ','',characteristic_table) %>% DataFrame();characteristic_data_frame
#colnames(characteristic_data_frame) <- gsub(':.*','',data_characteristic[[1]])
colnames(characteristic_data_frame) <- c('Gender','Ethnicity','TBStatus','Tissue')
row.names(characteristic_data_frame) <- names(GSMList(gse))

GSE42830_summarizedExperiemnt <- SummarizedExperiment(assays = list(GSE42830_Non_normalized_counts= as.matrix(GSE42830_Non_normalized_counts)), colData = characteristic_data_frame, rowData = row_data, metadata = list(GSE42830_experimentData)); GSE42830_summarizedExperiemnt
```

```{r}
saveRDS(GSE42830_summarizedExperiemnt, ascii=FALSE, file='~/Desktop/RA work/build_TB_data/Signatures/Bloom/GSE42830/GSE42830_summarizedExperiemnt.RDS')

# Remove files in temporary directory
unlink(paste0(normalizePath(tempdir()), "/", dir(tempdir())), recursive = TRUE)
dir(tempdir()) # check the temporary directory is empty


```

### Make a matrix contain the NA's for the TB status cariter
#### Standard column names come from Berry GSE19443
```{r}
getwd()
geo_access <- 'GSE42830'
sobject <- readRDS(paste0(geo_access,'/',geo_access,'_summarizedExperiemnt.RDS'))
```

```{r create new column information data}
standard_name_seq <- colData(readRDS('~/Desktop/RA work/build_TB_data/Signatures/Berry/GSE19443/GSE19443_summarizedExperiemnt.RDS')) %>% data.frame() %>% colnames
new_coldata <- function(sobject){
  col_info <- colData(sobject) %>% data.frame()
  dat_NA_new <- matrix(c(rep('n.a.',length(standard_name_seq)*nrow(col_info))),ncol=length(standard_name_seq),
                             byrow=T,dimnames=list(row.names(col_info),
                                                   standard_name_seq)) %>% data.frame()
  
  # fill in with existing data
  overlap_name <- standard_name_seq[which(colnames(dat_NA_new) %in% colnames(col_info))]
  for (i in overlap_name){
    dat_NA_new[i] <- col_info[i]
  }
  
  # Append the rest of cloumns to the dataframe
  col_info_rest <- col_info %>% dplyr::select(-overlap_name)
  dat_final <- cbind(dat_NA_new,col_info_rest)
  
  return(dat_final)
}

new_col_info <- new_coldata(sobject)

```

# Rename TBstatus
### PTB: active TB
### Latent
### Control
### OD: other disease
```{r}
TBStatus <- TBStatus_temp <- as.character(new_col_info$TBStatus)
unique(TBStatus_temp)

for(i in 1:length(TBStatus)){
  if(TBStatus_temp[i]=="TB"){
    TBStatus[i] = 'PTB'
  }
    if(TBStatus_temp[i]!="TB" & TBStatus_temp[i]!="Control"){
    TBStatus[i] = 'OD'
    }
}
TBStatus

new_col_info$TBStatus <- TBStatus
new_col_info$Notes <- TBStatus_temp
new_col_info$Gender <- ifelse(new_col_info$Gender=="M","Male","Female")
new_col_info$GeographicalRegion <- "Germany"
new_col_info$Notes <- ifelse(new_col_info$Notes=="Baseline","Pneumonia",new_col_info$Notes)

new_col_info %>% View()

colData(sobject) <- new_col_info %>% DataFrame()

```

# Edit Row Data

```{r}
row_data <- rowData(sobject) %>% data.frame()
row_data %>% View()

create_gene_symbol <- function(sobject){
  row_data <- rowData(sobject) %>% data.frame()
  Symbol_R <- row_data$SYMBOL 
  Symbol_plat <- row_data$Symbol
  
  # Use platform annotation as reference 
  Symbol_plat_new <- Symbol_plat
  for (i in 1:length(Symbol_R)){
    if (Symbol_plat_new[i]==""){
    Symbol_plat_new[i] = Symbol_R[i]
    }
  }
  row_data$SYMBOL_NEW <- Symbol_plat_new
  
  return(row_data)
}

create_gene_symbol(sobject) %>% View()
rowData(sobject) <- create_gene_symbol(sobject) %>% DataFrame()

saveRDS(sobject,paste0(geo_access,'/',geo_access,'_sobject.RDS'))

```


