---
title: "GSE69581"
author: "Xutao Wang"
date: "9/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import Packages
```{r libraries, message = FALSE, cache=TRUE}
library(GEOquery)
library(preprocessCore)
library(SummarizedExperiment)
library(limma)
library(dplyr)
library(illuminaHumanv4.db) # Illumina HumanHT-12 V4.0 expression beadchip
```

## Read in Non-normalized data
```{r, cache = TRUE}
#setwd('~/Desktop/RA work/build_TB_data/Signatures/Esmail')
urls = getGEOSuppFiles("GSE69581", fetch_files = FALSE)
url_non_normalized <- as.character(urls$url[1])

temp <- tempfile()
download.file(url_non_normalized,temp)

GSE69581_Non_normalized <- read.delim(gzfile(temp), row.names = 1, header = TRUE)
dim(GSE69581_Non_normalized)
```
```{r}
# Remove .PValue
GSE69581_Non_normalized <- GSE69581_Non_normalized[,-grep('PValue',colnames(GSE69581_Non_normalized))]
dim(GSE69581_Non_normalized)
```

```{r get corresponding sample ID , cache=TRUE}
# Obtain raw data information from GEO
gse <- getGEO("GSE69581", GSEMatrix =  F)
description_id_raw <- sapply(1:length(names(GSMList(gse))), 
                             function(x) GSMList(gse)[[x]]@dataTable@columns$Column[3])
# convert PValue_9421742028_J to 9421742028_J
description_id <- sapply(1:length(description_id_raw), 
                         function(x) gsub("^(.*?)_", "", description_id_raw[x]))
ID_table <- data.frame(SampleID = names(GSMList(gse)), DescriptionID = description_id)
head(ID_table)
```

```{r mapping DescriptionID to sampleID}
# Convert X9421742043_G to 9421742043_G
colnames(GSE69581_Non_normalized) <- sapply(1:ncol(GSE69581_Non_normalized), 
                             function(x) gsub("^(.*?)X", "", colnames(GSE69581_Non_normalized)[x]))
indx <- sapply(1:length(ID_table$DescriptionID), 
              function(i) which(colnames(GSE69581_Non_normalized) %in% ID_table$DescriptionID[i]));indx

GSE69581_Non_normalized <- GSE69581_Non_normalized[,indx]
colnames(GSE69581_Non_normalized) <- ID_table$SampleID
GSE69581_Non_normalized_counts <- GSE69581_Non_normalized
colnames(GSE69581_Non_normalized)[1:10]
```

```{r convert ProbeID to Gene Symbol, cache=TURE}
# Read in data from vendor's information
GPL10558_HumanHT <- getGEO('GPL10558', GSEMatrix = F)
GPL10558_HumanHT_dat <- GPL10558_HumanHT@dataTable@table

# Annotation
PROBES <- row.names(GSE69581_Non_normalized) # Should subsitute to Normalized file
OUT <- AnnotationDbi::select(illuminaHumanv4.db, PROBES, "SYMBOL")
OUT[is.na(OUT)] <- NA

# Map ProbeID to Gene Symbol 
OUT_collapse <- OUT %>% group_by(PROBEID) %>%  # Multiple gene symbols map to the same ProbeID
  summarise(SYMBOL = paste(SYMBOL, collapse="///"), times = length(unlist(strsplit(SYMBOL, "///")))) 

GSE69581_Non_normalized$ID_REF <- row.names(GSE69581_Non_normalized)
GSE69581_final <- GSE69581_Non_normalized %>% left_join(OUT_collapse, by=c('ID_REF' = "PROBEID")) %>% left_join(GPL10558_HumanHT_dat, by = c('ID_REF'='ID')) 

# Create Row data annotation
row_data <- GSE69581_final %>% dplyr::select(-grep('GSM',colnames(GSE69581_final))) %>% DataFrame()

#arrange(GSE69581_final, desc(times))
```

```{r}
# Create Column data annotation
data_characteristic <- lapply(1:length(GSMList(gse)), function(x)  
  GSMList(gse)[[x]]@header$characteristics_ch1)
characteristic_table <- sapply(1:length(data_characteristic[[1]]), function(x) 
  sapply(data_characteristic, '[[',x)) 

characteristic_data_frame <- sub('(.*?): ','',characteristic_table) %>% data.frame()
characteristic_data_frame <- mutate(characteristic_data_frame, Barcode=ID_table$DescriptionID) %>% DataFrame()
#colnames(characteristic_data_frame) <- gsub(':.*','',data_characteristic[[1]])
colnames(characteristic_data_frame) <- c('Tissue','HIVStatus','AntiRetroviralTherapy','TBStatus','Timepoint','StudyNumber','Barcode')
row.names(characteristic_data_frame) <- colnames(GSE69581_Non_normalized_counts)
head(characteristic_data_frame)
```


```{r create summarizedExperiment, cache=TRUE}
# Create Metadata
GSE69581_experimentData <- new('MIAME',
                      name="Hanif Esmail",
                      lab="University of Cape Town",
                      contact="hanif.esmail@ndcls.ox.ac.uk",
                      title="Complement Pathway Gene Activation and Rising Circulating Immune Complexes Characterize Early Disease in HIV-Associated Tuberculosis",
                      abstract="Total RNA extracted from whole blood of 35 HIV infected participants with evidence of latent TB (10 with subclinical pathology on PET/CT and 25 without) and 15 HIV infected participants with active TB",
                      url="10.1073/pnas.1711853115",
                      pubMedIds = '29339504',
                      other=list(platform = 'Illumina HumanHT-12 V4.0 expression beadchip (GPL10558)'))

GSE69581_summarizedExperiemnt <- SummarizedExperiment(assays = list(GSE69581_Non_normalized_counts= as.matrix(GSE69581_Non_normalized_counts)), colData = characteristic_data_frame, rowData = row_data, metadata = list(GSE69581_experimentData)); GSE69581_summarizedExperiemnt

```


```{r}
#'~/Desktop/RA work/build_TB_data/Signatures/Esmail/GSE69581/'
saveRDS(GSE69581_summarizedExperiemnt, ascii=FALSE, file='GSE69581/GSE69581_summarizedExperiemnt.RDS')

# Remove files in temporary directory
unlink(paste0(normalizePath(tempdir()), "/", dir(tempdir())), recursive = TRUE)
dir(tempdir()) # check the temporary directory is empty
```

### Make a matrix contain the NA's for the TB status cariter
#### Standard column names come from Berry GSE19443
```{r}
getwd()
geo_access <- 'GSE69581'
sobject <- readRDS(paste0(geo_access,'/',geo_access,'_summarizedExperiemnt.RDS'))
```

```{r create new column information data}
standard_name_seq <- colData(readRDS('~/Desktop/RA work/build_TB_data/Signatures/Berry/GSE19443/GSE19443_summarizedExperiemnt.RDS')) %>% data.frame() %>% colnames
new_coldata <- function(sobject){
  col_info <- colData(sobject) %>% data.frame()
  dat_NA_new <- matrix(c(rep('n.a.',length(standard_name_seq)*nrow(col_info))),ncol=length(standard_name_seq),
                             byrow=T,dimnames=list(row.names(col_info),
                                                   standard_name_seq)) %>% data.frame()
  
  # fill in with existing data
  overlap_name <- standard_name_seq[which(colnames(dat_NA_new) %in% colnames(col_info))]
  for (i in overlap_name){
    dat_NA_new[i] <- col_info[i]
  }
  
  # Append the rest of cloumns to the dataframe
  col_info_rest <- col_info %>% dplyr::select(-overlap_name)
  dat_final <- cbind(dat_NA_new,col_info_rest)
  
  return(dat_final)
}

new_col_info <- new_coldata(sobject)

```

# Rename TBstatus
### PTB: active TB
### Latent
### Control
### OD: other disease
```{r}
TBStatus <- TBStatus_temp <- as.character(new_col_info$TBStatus)
unique(TBStatus_temp)

for(i in 1:length(TBStatus)){
  if(TBStatus_temp[i]=="Active"){
    TBStatus[i] = 'PTB'
  }
    if(TBStatus_temp[i]=="Subclinical"){
    TBStatus[i] = 'OD'
    }
  
}
TBStatus

new_col_info$TBStatus <- TBStatus
new_col_info$HIVStatus <- "HIV positive"

new_col_info %>% View()

colData(sobject) <- new_col_info %>% DataFrame()

saveRDS(sobject,paste0(geo_access,'/',geo_access,'_sobject.RDS'))

```





