---
title: "GSE37250"
author: "Xutao Wang"
date: "10/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message = FALSE, cache=TRUE}
library(GEOquery)
library(preprocessCore)
library(SummarizedExperiment)
library(limma)
library(dplyr)
library(illuminaHumanv4.db) # Illumina HumanHT-12 V4.0 expression beadchip
library(GEOmetadb)
```

## Read in Non-normalized data, download the data directly from GEO
```{r}
#setwd('~/Desktop/RA work/build_TB_data/Signatures/Blankley')
urls <- getGEOSuppFiles('GSE37250', fetch_files = FALSE)
url_non_normalized <- as.character(urls$url[2])
temp <- tempfile()
download.file(url_non_normalized,temp)
GSE37250_Non_normalized <- read.delim(gzfile(temp),row.names = 1, header = TRUE)
```

```{r}
# Renaming column names
col_name_info <- c('SYMBOL',"SEARCH_KEY","ILMN_GENE","CHROMOSOME","DEFINITION","SYNONYMS")
GSE37250_col_name <- GSE37250_Non_normalized %>% as_tibble() %>% dplyr::select(col_name_info) %>% data.frame()
GSE37250_Non_pvalue <- GSE37250_Non_normalized %>% as_tibble() %>% dplyr::select(-c(col_name_info,grep('.Pval',colnames(GSE37250_Non_normalized)))) %>% data.frame()

dim(GSE37250_Non_pvalue)
```

```{r get corresponding sample ID , cache=TRUE}
# Obtain raw data information from GEO
gse <- getGEO("GSE37250", GSEMatrix =  F)
description_id_raw <- sapply(1:length(names(GSMList(gse))), 
                             function(x) GSMList(gse)[[x]]@dataTable@columns$Column[3])

description_id <- sapply(1:length(description_id_raw), 
                         function(x) gsub("\\..*", "", description_id_raw[x]))
ID_table <- data.frame(SampleID = names(GSMList(gse)), DescriptionID = description_id)
ID_table
```

```{r mapping DescriptionID to sampleID}
# Demo: convert X6247215025_L.AVG_Signal to 6247215025_L, should use \\. when mathcing . 
colnames(GSE37250_Non_pvalue) <- sapply(1:ncol(GSE37250_Non_pvalue), 
                             function(x) gsub(".*X|\\..*", "", colnames(GSE37250_Non_pvalue)[x]))

## Produce Simialr results for both methods
#indx <- rep(0,ncol(GSE37250_Non_pvalue))
#for (i in 1:length(colnames(GSE37250_Non_pvalue))){
#  indx[i] <- which(colnames(GSE37250_Non_pvalue) %in% ID_table$DescriptionID[i])
#}
indx <- sapply(1:length(colnames(GSE37250_Non_pvalue)), function(i) which(colnames(GSE37250_Non_pvalue) %in% ID_table$DescriptionID[i]))

GSE37250_Non_pvalue_reorgan <- GSE37250_Non_pvalue[,indx]
colnames(GSE37250_Non_pvalue_reorgan) <- ID_table$SampleID
row.names(GSE37250_Non_pvalue_reorgan) <- row.names(GSE37250_Non_normalized)

# Create Expression Matrix
GSE37250_Non_normalized_counts <- GSE37250_Non_pvalue_reorgan
colnames(GSE37250_Non_normalized_counts)[1:10]
```

```{r convert ProbeID to Gene Symbol, cache=TURE}
# Read in data from vendor's information
GPL10558_HumanHT <- getGEO('GPL10558', GSEMatrix = F)
GPL10558_HumanHT_dat <- GPL10558_HumanHT@dataTable@table

# Annotation
PROBES <- row.names(GSE37250_Non_pvalue_reorgan) 
OUT <- AnnotationDbi::select(illuminaHumanv4.db, PROBES, "SYMBOL")
OUT[is.na(OUT)] <- NA

# Map ProbeID to Gene Symbol 
OUT_collapse <- OUT %>% group_by(PROBEID) %>%  # Multiple gene symbols map to the same ProbeID
  summarise(SYMBOL = paste(SYMBOL, collapse="///"), times = length(unlist(strsplit(SYMBOL, "///")))) 

GSE37250_Non_pvalue_reorgan$ID_REF <- row.names(GSE37250_Non_pvalue_reorgan)
GSE37250_final <- GSE37250_Non_pvalue_reorgan %>% left_join(OUT_collapse, by=c('ID_REF'="PROBEID")) %>% left_join(GPL10558_HumanHT_dat, by = c('ID_REF'='ID')) 

# Create Row data annotation
row_data <- GSE37250_final %>% dplyr::select(-grep('GSM',colnames(GSE37250_final))) %>% DataFrame()
```


```{r}
# Create Column Data
data_characteristic <- lapply(1:length(GSMList(gse)), function(x)  
  GSMList(gse)[[x]]@header$characteristics_ch1)
characteristic_table <- sapply(1:length(data_characteristic[[1]]), function(x) 
  sapply(data_characteristic, '[[',x)) 
## Demo convert geographical region: Kenya to Kenya
characteristic_data_frame <- sub('(.*?): ','',characteristic_table) %>% as_tibble() %>% mutate(ID_table$DescriptionID) %>% DataFrame()

colnames(characteristic_data_frame) <- c('TBStatus','HIVStatus','GeographicalRegion','Tissue','DescriptionID')
row.names(characteristic_data_frame) <- names(GSMList(gse))
head(characteristic_data_frame)
```


```{r}
# Create Metadata
GSE37250_experimentData <- new('MIAME',
                      name="Victoria Wright",
                      lab="Imperial College London",
                      contact="v.wright@imperial.ac.uk",
                      title="Detection of tuberculosis in HIV-infected and -uninfected African adults using whole blood RNA expression signatures: a case-control study.",
                      abstract="Adults were recruited from Cape Town, South Africa (n=300) and Karonga, Malawi (n=237) who were either HIV+ or HIV - with either active TB, LTBI or OD. ",
                      url="10.1371/journal.pmed.1001538",
                      pubMedIds = '24167453',
                      other=list(Platform = 'Illumina HumanHT-12 V4.0 expression beadchip (GPL10558)'))

GSE37250_summarizedExperiemnt <- SummarizedExperiment(assays = list(GSE37250_Non_normalized_counts= as.matrix(GSE37250_Non_normalized_counts)), colData = characteristic_data_frame, rowData = row_data, metadata = list(GSE37250_experimentData)); GSE37250_summarizedExperiemnt

```

```{r}
saveRDS(GSE37250_summarizedExperiemnt, ascii=FALSE, file='~/Desktop/RA work/build_TB_data/Signatures/Blankley/GSE37250/GSE37250_summarizedExperiemnt.RDS')

# Remove files in temporary directory
unlink(paste0(normalizePath(tempdir()), "/", dir(tempdir())), recursive = TRUE)
dir(tempdir()) # check the temporary directory is empty
```

### Make a matrix contain the NA's for the TB status cariter
#### Standard column names come from Berry GSE19443
```{r}
getwd()
geo_access <- 'GSE37250'
sobject <- readRDS(paste0(geo_access,'/',geo_access,'_summarizedExperiemnt.RDS'))
```

```{r create new column information data}
standard_name_seq <- colData(readRDS('~/Desktop/RA work/build_TB_data/Signatures/Berry/GSE19443/GSE19443_summarizedExperiemnt.RDS')) %>% data.frame() %>% colnames
new_coldata <- function(sobject){
  col_info <- colData(sobject) %>% data.frame()
  dat_NA_new <- matrix(c(rep('n.a.',length(standard_name_seq)*nrow(col_info))),ncol=length(standard_name_seq),
                             byrow=T,dimnames=list(row.names(col_info),
                                                   standard_name_seq)) %>% data.frame()
  
  # fill in with existing data
  overlap_name <- standard_name_seq[which(colnames(dat_NA_new) %in% colnames(col_info))]
  for (i in overlap_name){
    dat_NA_new[i] <- col_info[i]
  }
  
  # Append the rest of cloumns to the dataframe
  col_info_rest <- col_info %>% dplyr::select(-overlap_name)
  dat_final <- cbind(dat_NA_new,col_info_rest)
  
  return(dat_final)
}

new_col_info <- new_coldata(sobject)

```

# Rename TBstatus
### PTB: active TB
### Latent
### Control
### OD: other disease
```{r}
TBStatus <- TBStatus_temp <- as.character(new_col_info$TBStatus)
unique(TBStatus_temp)
for(i in 1:length(TBStatus)){
  if(TBStatus_temp[i]=="active tuberculosis"){
    TBStatus[i] = 'PTB'
  }
    if(TBStatus_temp[i]=="latent TB infection"){
    TBStatus[i] = 'Latent'
    }
      if(TBStatus_temp[i]=="other disease"){
    TBStatus[i] = 'OD'
  }
}
TBStatus

new_col_info$TBStatus <- TBStatus

new_col_info %>% View()
colData(sobject) <- new_col_info %>% DataFrame()

```

# Edit Row Data

```{r}
row_data <- rowData(sobject) %>% data.frame()

create_gene_symbol <- function(sobject){
  row_data <- rowData(sobject) %>% data.frame()
  Symbol_R <- row_data$SYMBOL 
  Symbol_plat <- row_data$Symbol
  
  # Use platform annotation as reference 
  Symbol_plat_new <- Symbol_plat
  for (i in 1:length(Symbol_R)){
    if (Symbol_plat_new[i]==""){
    Symbol_plat_new[i] = Symbol_R[i]
    }
  }
  row_data$SYMBOL_NEW <- Symbol_plat_new
  
  return(row_data)
}

create_gene_symbol(sobject) %>% View()
rowData(sobject) <- create_gene_symbol(sobject) %>% DataFrame()

saveRDS(sobject,paste0(geo_access,'/',geo_access,'_sobject.RDS'))

```




