---
title: "GSE56153"
author: "Xutao Wang"
date: "10/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message = FALSE, cache=TRUE}
library(GEOquery)
library(preprocessCore)
library(SummarizedExperiment)
library(limma)
library(dplyr)
library(illuminaHumanv3.db) # Illumina HumanHT-12 V3.0 expression beadchip
```

## Read in Non-normalized data
```{r, cache = TRUE}
urls <- getGEOSuppFiles("GSE56153", fetch_files = FALSE)
url_non_normalized <- as.character(urls$url[2])
temp <- tempfile()
tempd <- tempdir()
download.file(url_non_normalized,temp)

GSE56153_Non_normalized <- read.delim(gzfile(temp),row.names = 1, header = TRUE)
head(GSE56153_Non_normalized)
```

```{r}
# Renaming column names, remove .Pval
GSE56153_Non_pvalue <- GSE56153_Non_normalized[,-grep('.Pval',colnames(GSE56153_Non_normalized))]
GSE56153_Non_normalized_counts <- GSE56153_Non_normalized[,-grep('.Pval',colnames(GSE56153_Non_normalized))]
dim(GSE56153_Non_pvalue)

gse <- getGEO("GSE56153", GSEMatrix =  F)
colnames(GSE56153_Non_pvalue) <- names(GSMList(gse))
colnames(GSE56153_Non_normalized_counts) <- names(GSMList(gse))
```

```{r convert ProbeID to Gene Symbol, cache=TURE}
# Annotation from vendor's information
gpl6883 <- getGEO("GPL6883", GSEMatrix = F)
GPL6883_dat <- gpl6883@dataTable@table %>% data.frame()

# Annotation
PROBES <- row.names(GSE56153_Non_pvalue) # Should subsitute to Normalized file???
OUT <- AnnotationDbi::select(illuminaHumanv3.db, PROBES, "SYMBOL")
OUT[is.na(OUT)] <- NA

# Map ProbeID to Gene Symbol 
OUT_collapse <- OUT %>% group_by(PROBEID) %>%  # Multiple gene symbols map to the same ProbeID
  summarise(SYMBOL = paste(SYMBOL, collapse="///"), times = length(unlist(strsplit(SYMBOL, "///")))) 

GSE56153_Non_pvalue$ID_REF <- row.names(GSE56153_Non_pvalue)
GSE56153_final <- GSE56153_Non_pvalue %>% left_join(OUT_collapse, by=c('ID_REF'="PROBEID")) %>% left_join(GPL6883_dat, by = c('ID_REF'='ID')) 

# Create Row data annotation
row_data <- GSE56153_final %>% dplyr::select(-grep('GSM',colnames(GSE56153_final))) %>% DataFrame()
#arrange(GSE56153_final, desc(times))
```

## Create ColData
```{r get column data, cache=TRUE}
data_characteristic <- lapply(1:length(GSMList(gse)), function(x)  
  GSMList(gse)[[x]]@header$characteristics_ch1)
characteristic_table <- sapply(1:length(data_characteristic[[1]]), function(x) 
  sapply(data_characteristic, '[[',x)) 
## Demo convert geographical region: Kenya to Kenya
characteristic_data_frame <- sub('(.*?): ','',characteristic_table) %>% DataFrame()

colnames(characteristic_data_frame) <- c('Tissue','Phenotype','Condition')
row.names(characteristic_data_frame) <- colnames(GSE56153_Non_normalized_counts)
head(characteristic_data_frame)
```

```{r Create RowData MetaData and summarized experiment}
# Create Metadata
GSE56153_experimentData <- new('MIAME',
                      name="Ahmad Nazri Mohamed Naim",
                      lab="Genome institute of Singapore",
                      contact="mohamedan@gis.a-star.edu.sg",
                      title="Genome-wide expression profiling identifies type 1 interferon response pathways in active tuberculosis.",
                      abstract="Overall Design: Total RNA obtained from human whole blood of TB patients longitudinally sampled along 3 time-points: during active infection, during treatment, and after completion of curative treatment",
                      url="10.1371/journal.pone.0045839",
                      pubMedIds = '23029268',
                      other=list(Platform = 'Illumina HumanRef-8 v3.0 expression beadchip (GPL6883)'))

GSE56153_summarizedExperiemnt <- SummarizedExperiment(assays = list(GSE56153_Non_normalized_counts= as.matrix(GSE56153_Non_normalized_counts)), colData = characteristic_data_frame, rowData = row_data, metadata = list(GSE56153_experimentData)); GSE56153_summarizedExperiemnt

```

```{r}
saveRDS(GSE56153_summarizedExperiemnt, ascii=FALSE, file='GSE56153/GSE56153_summarizedExperiemnt.RDS')

# Remove files in temporary directory
unlink(paste0(normalizePath(tempdir()), "/", dir(tempdir())), recursive = TRUE)
dir(tempdir()) # check the temporary directory is empty
```

### Make a matrix contain the NA's for the TB status cariter
#### Standard column names come from Berry GSE19443
```{r}
getwd()
geo_access <- 'GSE56153'
sobject <- readRDS(paste0(geo_access,'/',geo_access,'_summarizedExperiemnt.RDS'))
```

```{r create new column information data}
standard_name_seq <- colData(readRDS('~/Desktop/RA work/build_TB_data/Signatures/Berry/GSE19443/GSE19443_summarizedExperiemnt.RDS')) %>% data.frame() %>% colnames
new_coldata <- function(sobject){
  col_info <- colData(sobject) %>% data.frame()
  dat_NA_new <- matrix(c(rep('n.a.',length(standard_name_seq)*nrow(col_info))),ncol=length(standard_name_seq),
                             byrow=T,dimnames=list(row.names(col_info),
                                                   standard_name_seq)) %>% data.frame()
  
  # fill in with existing data
  overlap_name <- standard_name_seq[which(colnames(dat_NA_new) %in% colnames(col_info))]
  for (i in overlap_name){
    dat_NA_new[i] <- col_info[i]
  }
  
  # Append the rest of cloumns to the dataframe
  col_info_rest <- col_info %>% dplyr::select(-overlap_name)
  dat_final <- cbind(dat_NA_new,col_info_rest)
  
  return(dat_final)
}

new_col_info <- new_coldata(sobject)

```

# Rename TBstatus
### PTB: active TB
### Latent
### Control
### OD: other disease
```{r}
TBStatus <- TBStatus_temp <- as.character(new_col_info$TBStatus)
unique(TBStatus_temp)
TBStatus <- ifelse(TBStatus_temp=='LTB','Latent',TBStatus_temp)
TBStatus

new_col_info$TBStatus <- 'PTB'
new_col_info <- new_col_info[,-which(colnames(new_col_info)=='Phenotype')]

new_col_info %>% View()

colData(sobject) <- new_col_info %>% DataFrame()

saveRDS(sobject,paste0(geo_access,'/',geo_access,'_sobject.RDS'))

```



