---
title: "GSE54992"
author: "Xutao Wang"
date: "9/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message = FALSE, cache=TRUE}
library(GEOquery)
library(preprocessCore)
library(SummarizedExperiment)
library(affy)
library(dplyr)
library(hgu133plus2.db) # Affymetrix Human Genome U133 Plus 2.0 Array
```

## Read in Non-normalized data
```{r, cache = TRUE}
setwd('~/Desktop/RA work/build_TB_data/Signatures/Blankley')
getwd()
filePaths = getGEOSuppFiles("GSE54992")
untar('GSE54992/GSE54992_RAW.tar', exdir="GSE54992/GSE54992_Raw")
celFiles <- list.celfiles(path = "GSE54992/GSE54992_Raw", full.names=TRUE)
GSE54992_data.affy <- ReadAffy(filenames = celFiles)

# Conduct RMA
#GSE54992_Non_normalized <- GSE54992_data.affy@assayData$exprs
GSE54992_normalized_rma <- exprs(rma(GSE54992_data.affy)) # A matrix

# Convert GSM1327554_36363.CEL.gz to GSM1327554
colnames(GSE54992_normalized_rma) <- sapply(1:ncol(GSE54992_normalized_rma), 
                                          function(x) gsub('_.*','',colnames(GSE54992_normalized_rma)[x]))
GSE54992_normalized_counts <- GSE54992_normalized_rma
GSE54992_normalized_counts[1:5,1:5]
```

```{r convert ProbeID to Gene Symbol, cache=TURE}
# Annotation
PROBES <- row.names(GSE54992_normalized_rma) # Should subsitute to Normalized file???
OUT <- AnnotationDbi::select(hgu133plus2.db, PROBES, "SYMBOL")
OUT[is.na(OUT)] <- 'Unmapped'

# Map ProbeID to Gene Symbol 
OUT_collapse <- OUT %>% group_by(PROBEID) %>%  # Multiple gene symbols map to the same ProbeID
  summarise(SYMBOL = paste(SYMBOL, collapse=", "), times = length(unlist(strsplit(SYMBOL, ",")))) 

GSE54992_normalized_rma <- GSE54992_normalized_rma %>% as_tibble() %>% mutate(ID_REF=row.names(GSE54992_normalized_rma))
GSE54992_final <- OUT_collapse %>% left_join(GSE54992_normalized_rma, by=c("PROBEID" = 'ID_REF')) %>% as_tibble()

arrange(GSE54992_final, desc(times))
```

```{r create column data}
gse <- getGEO("GSE54992", GSEMatrix =  F)
data_characteristic <- lapply(1:length(GSMList(gse)), function(x)  
  GSMList(gse)[[x]]@header$characteristics_ch1)
characteristic_table <- sapply(1:length(data_characteristic[[1]]), function(x) 
  sapply(data_characteristic, '[[',x)) 
## Demo convert geographical region: Kenya to Kenya
characteristic_data_frame <- sub('(.*?): ','',characteristic_table) %>% DataFrame()
#colnames(characteristic_data_frame) <- gsub(':.*','',data_characteristic[[1]])
# Get string between two words
characteristic_data_frame$TimePostTreatment <- gsub('.*for (.+).*','\\1',characteristic_data_frame$V1)
characteristic_data_frame$TimePostTreatment[-grep('month',characteristic_data_frame$TimePostTreatment)] <-'n.a.'

characteristic_data_frame$TBStatus <- plyr::revalue(characteristic_data_frame$V1,c('tuberculosis'='TB','TB patient after anti-tuberculosis treatment for 3 months'='TB_treatment','TB patient after anti-tuberculosis treatment for 6 months'='TB_treatment','latent tuberculosis infection'='latent','healthy donor'='control'))
characteristic_data_frame$Tissue <- characteristic_data_frame$V2
characteristic_data_frame <- characteristic_data_frame[,-c(1,2)]

row.names(characteristic_data_frame) <- colnames(GSE54992_normalized_counts)
head(characteristic_data_frame)
```

```{r Create RowData MetaData and summarized experiment}
# Create Row data annotation
row_data <- DataFrame(SYMBOL=GSE54992_final$SYMBOL)

# Create Metadata
GSE54992_experimentData <- new('MIAME',
                      name="Xinchun Chen",
                      lab="Shenzhen Third People's Hospital",
                      contact="chenxinchun@hotmail.com",
                      title="Increased complement C1q level marks active disease in human tuberculosis.",
                      abstract="An example SummarizedExperimentObject",
                      url="10.1371/journal.pone.0092340",
                      pubMedIds = '24647646',
                      other=list(Platform = 'Affymetrix Human Genome U133 Plus 2.0 Array'))

GSE54992_summarizedExperiemnt <- SummarizedExperiment(assays = list(GSEGSE54992_normalized_counts= as.matrix(GSE54992_normalized_counts)), colData = characteristic_data_frame, rowData = row_data, metadata = list(GSE54992_experimentData)); GSE54992_summarizedExperiemnt

```

```{r}
saveRDS(GSE54992_summarizedExperiemnt, ascii=FALSE, file='GSE54992/GSE54992_summarizedExperiemnt.RDS')
```




