---
title: "GSE6112"
author: "Xutao Wang"
date: "10/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(GEOquery)
library(preprocessCore)
library(SummarizedExperiment)
library(dplyr)
library(limma)
# install.packages("XML")
library(XML)
library(methods)
# MPIIB custom human (AMADID 011412)
```


```{r}
urls <-  getGEOSuppFiles("GSE6112",fetch_files = FALSE)
url_xml <- as.character(urls$url[1])
temp <- tempfile()
tempd <- tempdir()
download.file(url_xml,temp)
untar(temp,exdir = tempd)

xmlFiles <- list.files(path = tempd, pattern = '*.xml',full.names=TRUE);xmlFiles

library(xml2)
library(tidyverse)
GSE6112_xml <- lapply(xmlFiles, function(x) read_xml(x))
```

## Create Row Data
```{r}
# Extract reporter information, , gene & Probe features
row_data_list <- lapply(GSE6112_xml, function(x) xml_find_all(x, "//reporter") %>% map(xml_attrs) %>% 
        map_df(~as.list(.)))

# Expect each data is identical, check!
sum(sapply(1:length(row_data_list), function(x) all(row_data_list[[1]][,1] != row_data_list[[x]][,1])))
# Yes they are the same

row_data <- row_data_list[[1]]

# Annotation for the probe
GPL4475_raw <- getGEO("GPL4475", GSEMatrix =  F)

# Remove duplicated Sequence Name
GPL4475_annotate <- GPL4475_raw@dataTable@table %>% distinct(`Primary Sequence Name`, .keep_all = TRUE) %>% filter(`Primary Sequence Name`!='')
row_data_final <- row_data %>% left_join(GPL4475_annotate, by=c('systematic_name' = 'Primary Sequence Name')) %>% DataFrame()
head(row_data_final)
```

## Create Column Data
```{r}
gse <- getGEO("GSE6112", GSEMatrix =  F)

# Create Column Data
# Two characteristics from each sample, b.c this study is about comparison
data_characteristic_1 <- lapply(1:length(GSMList(gse)), function(x)  
  GSMList(gse)[[x]]@header$characteristics_ch1)
data_characteristic_2 <- lapply(1:length(GSMList(gse)), function(x)  
  GSMList(gse)[[x]]@header$characteristics_ch2)

characteristic_table_1 <- sapply(1:length(data_characteristic_1[[1]]), function(x) 
  sapply(data_characteristic_1, '[[',x)) 
head(characteristic_table_1)

characteristic_table_2 <- sapply(1:length(data_characteristic_2[[1]]), function(x) 
  sapply(data_characteristic_2, '[[',x)) 
head(characteristic_table_2)

characteristic_data_frame <- rbind(characteristic_table_1,characteristic_table_2) %>% DataFrame()

colnames(characteristic_data_frame) <- c('TBStatus')
character_row_name <- rep(names(GSMList(gse)),2)
#for(i in 1:length(character_row_name)){
#  if(i%%2 != 0){
#    character_row_name[i] <- paste0(character_row_name[i],'_ch1')
#  }
#  else{
#    character_row_name[i] <- paste0(character_row_name[i],'_ch2')
#  }
#}
character_row_name_1 <- paste0(character_row_name[1:36],'_ch1')
character_row_name_2 <- paste0(character_row_name[37:72],'_ch2')
character_row_name <- c(character_row_name_1,character_row_name_2)
row.names(characteristic_data_frame) <- character_row_name
characteristic_data_frame
```

# Create Expression Matrix (raw and normalized) for channel 1 and channel 2
```{r}
GSE6112_raw_counts <- lapply(GSE6112_xml, function(x) xml_find_all(x, "//signal") %>% map(xml_attrs) %>% 
        map_df(~as.list(.)))

# For Channel 1 raw value, get odd index
GSE6112_raw_data_ch1 <- lapply(GSE6112_raw_counts, function(x) x %>% filter(as.numeric(row.names(x))%%2 != 0) %>% dplyr::select(raw_value))
GSE6112_raw_value_ch1 <- do.call(cbind,GSE6112_raw_data_ch1) 
colnames(GSE6112_raw_value_ch1) <- character_row_name_1

# For Channel 2 normalized value, get even index
GSE6112_raw_data_ch2 <- lapply(GSE6112_raw_counts, function(x) x %>% filter(as.numeric(row.names(x))%%2 == 0) %>% dplyr::select(raw_value))
GSE6112_raw_value_ch2 <- do.call(cbind,GSE6112_raw_data_ch2) 
colnames(GSE6112_raw_value_ch2) <- character_row_name_2

GSE6112_raw_value <- cbind(GSE6112_raw_value_ch1,GSE6112_raw_value_ch2)
```

# Create SummarizedExperiment Object
```{r}
# Create Metadata
GSE6112_experimentData <- new('MIAME',
                      name="Marc Jacobsen",
                      lab="Max-Planck-Institute for Infection Biology",
                      contact="jacobsen@mpiib-berlin.mpg.de",
                      title="Candidate biomarkers for discrimination between infection and disease caused by Mycobacterium tuberculosis.",
                      abstract="Comparison of PBMC tuberculosis patients and healthy infected control donors via an reference RNA pool from non-infected controls",
                      url="10.1007/s00109-007-0157-6",
                      pubMedIds = '17318616',
                      other=list(Platform = 'MPIIB custom human (AMADID 011412): GPL4475
'))

GSE6112_summarizedExperiemnt <- SummarizedExperiment(assays = list(GSE6112_Non_normalized_counts= as.matrix(GSE6112_raw_value)), colData = characteristic_data_frame, rowData = row_data_final, metadata = list(GSE6112_experimentData)); GSE6112_summarizedExperiemnt

```

## Add Normalized reads
```{r}
# For Channel 1 normalized value
GSE6112_norm_data_ch1 <- lapply(GSE6112_raw_counts, function(x) x %>% filter(as.numeric(row.names(x))%%2 != 0) %>% dplyr::select(normalized_value))
GSE6112_norm_value_ch1 <- do.call(cbind,GSE6112_norm_data_ch1) 
colnames(GSE6112_norm_value_ch1) <- character_row_name_1

# For Channel 2 normalized value
GSE6112_norm_data_ch2 <- lapply(GSE6112_raw_counts, function(x) x %>% filter(as.numeric(row.names(x))%%2 == 0) %>% dplyr::select(normalized_value))
GSE6112_norm_value_ch2 <- do.call(cbind,GSE6112_norm_data_ch2) 
colnames(GSE6112_norm_value_ch2) <- character_row_name_2

GSE6112_norm_value <- cbind(GSE6112_norm_value_ch1,GSE6112_norm_value_ch2)

assay(GSE6112_summarizedExperiemnt, "GSE6112_normalized_counts") <- as.matrix(GSE6112_norm_value)
```

```{r}
saveRDS(GSE6112_summarizedExperiemnt, ascii=FALSE, file='GSE6112/GSE6112_summarizedExperiemnt.RDS')

# Remove files in temporary directory
unlink(paste0(normalizePath(tempdir()), "/", dir(tempdir())), recursive = TRUE)
dir(tempdir()) # check the temporary directory is empty
```







```{r}
### Demo, DO NOT include in the summarized experiment###########
nrows <- 20; ncols <- 6
counts <- matrix(runif(nrows * ncols, 1, 1e4), nrows)
rowRanges <- GRanges(rep(c("chr1", "chr2"), c(5, 15)),
                         IRanges(sample(1000L, 20), width=100),
                         strand=Rle(c("+", "-"), c(12, 8)))
colData <- DataFrame(Treatment=rep(c("ChIP", "Input"), 3),
                         row.names=LETTERS[1:6])
rse0 <- SummarizedExperiment(assays=SimpleList(counts=counts),
                                 rowRanges=rowRanges, colData=colData)
assay(rse0, "logs") <- log(counts)
assays(rse0)$counts
```


### Make a matrix contain the NA's for the TB status cariter
#### Standard column names come from Berry GSE19443
```{r}
getwd()
geo_access <- 'GSE6112'
sobject <- readRDS(paste0(geo_access,'/',geo_access,'_summarizedExperiemnt.RDS'))
```

```{r create new column information data}
standard_name_seq <- colData(readRDS('~/Desktop/RA work/build_TB_data/Signatures/Berry/GSE19443/GSE19443_summarizedExperiemnt.RDS')) %>% data.frame() %>% colnames
new_coldata <- function(sobject){
  col_info <- colData(sobject) %>% data.frame()
  dat_NA_new <- matrix(c(rep('n.a.',length(standard_name_seq)*nrow(col_info))),ncol=length(standard_name_seq),
                             byrow=T,dimnames=list(row.names(col_info),
                                                   standard_name_seq)) %>% data.frame()
  
  # fill in with existing data
  overlap_name <- standard_name_seq[which(colnames(dat_NA_new) %in% colnames(col_info))]
  for (i in overlap_name){
    dat_NA_new[i] <- col_info[i]
  }
  
  # Append the rest of cloumns to the dataframe
  col_info_rest <- col_info %>% dplyr::select(-overlap_name)
  dat_final <- cbind(dat_NA_new,col_info_rest)
  
  return(dat_final)
}

new_col_info <- new_coldata(sobject)

```

# Rename TBstatus
### PTB: active TB
### Latent
### Control
### OD: other disease
```{r}
new_col_info$Tissue <- 'PBMC'
new_col_info$Notes <- new_col_info$TBStatus

TBStatus <- TBStatus_temp <- as.character(new_col_info$TBStatus)
unique(TBStatus_temp)

TBStatus[grep('LTBI',TBStatus_temp)] <- 'Latent'
TBStatus[grep('Healthy',TBStatus_temp)] <- 'Latent'
TBStatus[grep('_TB_',TBStatus_temp)] <- 'PTB'
TBStatus[grep('Pool',TBStatus_temp)] <- 'Control'
TBStatus


new_col_info$TBStatus <- TBStatus

new_col_info %>% View()

colData(sobject) <- new_col_info %>% DataFrame()

```

# Edit Row information
```{r}
row_info <- rowData(sobject) %>% data.frame()
View(row_info)

saveRDS(sobject,paste0(geo_access,'/',geo_access,'_sobject.RDS'))

```
























































































